### ISSUE TITLE
Compare ruODK with other R packages related to ODK or OData

### ISSUE THREAD

**Issue by florianm** [dbca-wa/ruODK#25]
## Feature
Source https://github.com/ropensci/software-review/issues/335#issuecomment-529793170
@maelle

### Examples

* https://ropensci.github.io/CoordinateCleaner/articles/Background_comparison_other_software.html
* https://rtweet.info/#package-functionality

#### ODK 

* https://github.com/validmeasures/odkr
* https://cran.r-project.org/web/packages/odk/index.html
* https://github.com/nap2000/odkmeta and fork https://github.com/LloydOBanwart/odkmeta

#### OData

* https://github.com/HanOostdijk/odataR
* https://cran.r-project.org/web/packages/cbsodataR/
* https://cran.r-project.org/web/packages/OData/index.html
* https://www.cdata.com/kb/tech/odata-jdbc-r.rst

Note to self: chuck in a reference to https://www.odata.org/

**Comment by maelle** [comment]
Should https://unhcr.github.io/koboloadeR/docs/ be included?

**Comment by florianm** [comment]
Nice one, will include. Looks like targeted towards Kobotoolbox, which is also based on ODK.
