### ISSUE TITLE
get_one_submission returns NULL

### ISSUE THREAD

**Issue by arestrom** [dbca-wa/ruODK#50]
## Problem
In testing the majority of ruODK functions all seem to work well so far...with the exception of the `get_submission()` functions. However, when I edited the `get_one_submission()` function and removed `magrittr::extract2("data")` it all worked and submissions downloaded as expected. 

## Reproducible example
```{r}
# Amended function works...but get_one_submission() returned NULLs
get_single_submission <- function(
  iid,
  pid = get_default_pid(),
  fid = get_default_fid(),
  url = get_default_url(),
  un = get_default_un(),
  pw = get_default_pw()) {
  glue::glue("{url}/v1/projects/{pid}/forms/{fid}/submissions/{iid}.xml") %>%
    httr::GET(httr::authenticate(un, pw)) %>%
    httr::content(.) %>%
    xml2::as_list(.)
}
```
<details>
<summary><strong>Session Info</strong></summary>
  
```{r}
# utils::sessionInfo()
```
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.8.4      ruODK_0.6.6.9009

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3           rstudioapi_0.10      xml2_1.2.2           knitr_1.27           magrittr_1.5         tidyselect_1.0.0    
 [7] R6_2.4.1             rlang_0.4.3.9000     fansi_0.4.1          stringr_1.4.0        httr_1.4.1           tools_3.6.2         
[13] xfun_0.12            utf8_1.1.4           cli_2.0.1            assertthat_0.2.1     tibble_2.1.3         lifecycle_0.1.0.9000
[19] crayon_1.3.4         purrr_0.3.3.9000     fs_1.3.1             vctrs_0.2.99.9005    curl_4.3             glue_1.3.1          
[25] stringi_1.4.5        compiler_3.6.2       pillar_1.4.3         jsonlite_1.6         lubridate_1.7.4      pkgconfig_2.0.3  

</details>

**Comment by florianm** [comment]
Hmm, I can't reproduce the NULL with the example data from the package tests.
What data did you use to trigger the bug?

``` r
library(magrittr)
library(ruODK)
ruODK::ru_settings()
#> <ruODK settings>
#>   Default ODK Central Project ID:  1 
#>   Default ODK Central Form ID:  build_Predator-or-Disturbance-1-1_1559789410 
#>   Default ODK Central URL:  https://odkcentral.dbca.wa.gov.au 
#>   Default ODK Central Username:  florian.mayer@dbca.wa.gov.au 
#>   Default ODK Central Password: run ruODK::get_default_pw() to show 
#>   Test ODK Central Project ID: 14 
#>   Test ODK Central Form ID: build_Flora-Quadrat-0-4_1564384341 
#>   Test ODK Central Form ID (ZIP tests): build_Spotlighting-0-6_1558333698 
#>   Test ODK Central Form ID (Attachment tests): build_Flora-Quadrat-0-1_1558330379 
#>   Test ODK Central Form ID (Parsing tests): build_Turtle-Track-or-Nest-1-0_1569907666 
#>   Test ODK Central URL: https://sandbox.central.opendatakit.org 
#>   Test ODK Central Username: Florian.Mayer@dbca.wa.gov.au 
#>   Test ODK Central Password: run ruODK::get_test_pw() to show
sl <- ruODK::submission_list()
ruODK::get_one_submission(sl$instance_id[[1]])
#> $meta
#> $meta$instanceID
#> $meta$instanceID[[1]]
#> [1] "uuid:5f37dffb-43b9-4559-99c2-cbb4285ad01e"
#> 
#> 
#> 
#> $observation_start_time
#> $observation_start_time[[1]]
#> [1] "2020-01-28T05:33:18.151+08:00"
#> 
#> 
#> $reporter
#> $reporter[[1]]
#> [1] "Bruce Pennicuik"
#> 
#> 
#> $device_id
#> $device_id[[1]]
#> [1] "f73d2e1221ceaa06"
#> 
#> 
#> $disturbanceobservation
#> $disturbanceobservation$location
#> $disturbanceobservation$location[[1]]
#> [1] "-17.91145062 122.21126666 29.57769775390625 4.288"
#> 
#> 
#> $disturbanceobservation$photo_disturbance
#> $disturbanceobservation$photo_disturbance[[1]]
#> [1] "1580160820438.jpg"
#> 
#> 
#> $disturbanceobservation$disturbance_cause
#> $disturbanceobservation$disturbance_cause[[1]]
#> [1] "goanna"
#> 
#> 
#> $disturbanceobservation$disturbance_cause_confidence
#> $disturbanceobservation$disturbance_cause_confidence[[1]]
#> [1] "expert-opinion"
#> 
#> 
#> $disturbanceobservation$comments
#> $disturbanceobservation$comments[[1]]
#> [1] "2 goanna tracks leading in. Small dig no shells"
#> 
#> 
#> 
#> $observation_end_time
#> $observation_end_time[[1]]
#> [1] "2020-01-28T05:34:24.993+08:00"
#> 
#> 
#> attr(,"id")
#> [1] "build_Predator-or-Disturbance-1-1_1559789410"
#> attr(,"xmlns:h")
#> [1] "http://www.w3.org/1999/xhtml"
#> attr(,"xmlns:xsd")
#> [1] "http://www.w3.org/2001/XMLSchema"
#> attr(,"xmlns:jr")
#> [1] "http://openrosa.org/javarosa"

get_single_submission <- function(
  iid,
  pid = get_default_pid(),
  fid = get_default_fid(),
  url = get_default_url(),
  un = get_default_un(),
  pw = get_default_pw()) {
  glue::glue("{url}/v1/projects/{pid}/forms/{fid}/submissions/{iid}.xml") %>%
    httr::GET(httr::authenticate(un, pw)) %>%
    httr::content(.) %>%
    xml2::as_list(.)
}
get_single_submission(sl$instance_id[[1]])
#> $data
#> $data$meta
#> $data$meta$instanceID
#> $data$meta$instanceID[[1]]
#> [1] "uuid:5f37dffb-43b9-4559-99c2-cbb4285ad01e"
#> 
#> 
#> 
#> $data$observation_start_time
#> $data$observation_start_time[[1]]
#> [1] "2020-01-28T05:33:18.151+08:00"
#> 
#> 
#> $data$reporter
#> $data$reporter[[1]]
#> [1] "Bruce Pennicuik"
#> 
#> 
#> $data$device_id
#> $data$device_id[[1]]
#> [1] "f73d2e1221ceaa06"
#> 
#> 
#> $data$disturbanceobservation
#> $data$disturbanceobservation$location
#> $data$disturbanceobservation$location[[1]]
#> [1] "-17.91145062 122.21126666 29.57769775390625 4.288"
#> 
#> 
#> $data$disturbanceobservation$photo_disturbance
#> $data$disturbanceobservation$photo_disturbance[[1]]
#> [1] "1580160820438.jpg"
#> 
#> 
#> $data$disturbanceobservation$disturbance_cause
#> $data$disturbanceobservation$disturbance_cause[[1]]
#> [1] "goanna"
#> 
#> 
#> $data$disturbanceobservation$disturbance_cause_confidence
#> $data$disturbanceobservation$disturbance_cause_confidence[[1]]
#> [1] "expert-opinion"
#> 
#> 
#> $data$disturbanceobservation$comments
#> $data$disturbanceobservation$comments[[1]]
#> [1] "2 goanna tracks leading in. Small dig no shells"
#> 
#> 
#> 
#> $data$observation_end_time
#> $data$observation_end_time[[1]]
#> [1] "2020-01-28T05:34:24.993+08:00"
#> 
#> 
#> attr(,"id")
#> [1] "build_Predator-or-Disturbance-1-1_1559789410"
#> attr(,"xmlns:h")
#> [1] "http://www.w3.org/1999/xhtml"
#> attr(,"xmlns:xsd")
#> [1] "http://www.w3.org/2001/XMLSchema"
#> attr(,"xmlns:jr")
#> [1] "http://openrosa.org/javarosa"
```

<sup>Created on 2020-02-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by arestrom** [comment]
Interesting. I created a simplified version of the form that generated the issue and the get_one_submission() function worked as expected. I then used the XLSForm Online tool to regenerate an xml of the exact same form that produced the issue and again the test submissions downloaded correctly using the original ruODK::get_one_submission() function. I did notice that there was an update to the XLSForm Online tool yesterday that included a breaking change in the xml structure, so not sure if that is what might have been responsible for the difference in behavior. Regardless, all is well and this issue (question) can be closed.

**Comment by florianm** [comment]
Thanks for the follow-up! 

I've built all forms in ODK Build and exported them as XForms. XLSForms support in ODK Central is relatively new, so I haven't gone down that route yet.

**Comment by arestrom** [comment]
Yes I suspect a slight difference in the build may have been the cause, but
won't investigate further now that the process is working.

I just finished updating all scripts to use ruODK and everything is working
perfectly. Thanks so much for a truly beautiful package. For the past few
years I've used the Briefcase CLI in tandem with R Shiny front-ends on a
variety of projects to pull data from Aggregate servers hosted on GAE. I've
been looking forward to trying central and ruODK given the new, improved
API. I could not be happier with the results. The only tweak I've made is
to customize the ru_setup() function with a verbose = FALSE option...but
that's just personal preference. Thanks again!

**Comment by florianm** [comment]
wow, thanks for the kind words! Great to see ruODK being used in the wild :-)

**Comment by florianm** [comment]
@arestrom thanks for the idea of a global verbosity setting - is #51 roughly what you were after?

**Comment by arestrom** [comment]
Yes, the idea of a global setting for both verbosity and timezone is an
excellent enhancement. My original tweak was just to quiet the ru_setup()
print statement...with something like: if (verbose == TRUE )
print(ru_settings()). It's good to see the print output from ru_setup()
during development, but I like having the option to quiet that output
during production.

The one bit of verbosity I do like to see during production is the message
in attachment_get() that notifies of a successful write to the media
directory. So the ability to override global settings depending on the
function can be useful.

**Comment by florianm** [comment]
That makes a lot of sense, thanks! Now `ru_setup()` prints only of `get_ru_verbose()` returns `TRUE`.

As `attachment_get()` is called by `odata_submission_get()`, the "golden path" use case of `odata_submission_get(wkt=T, parse=T,verbose=T)` will get verbose messages from `odata_submission_get()`, `odata_submission_parse()`, and `attachment_get()`.
