### ISSUE TITLE
Should we use usethis::use_pkgdown_travis()?

### ISSUE THREAD

**Issue by florianm** [dbca-wa/ruODK#52]
## Feature
Since rOpenSci appears to host and theme pkgdown sites, although I can't really tell from https://devguide.ropensci.org/ci.html#even-more-ci-ropensci-docs what build process is used (Jenkins seems to be involved).

@maelle @sckott would it be helpful if ruODK were to build its site via `usethis::use_pkgdown_travis()`?
The main challenge might be the embedded media files. Solved example:

* [make_data](https://github.com/dbca-wa/rGeoCBI/blob/master/data-raw/make_data.R) prepares files and generates vignette header
* [vignette](https://github.com/dbca-wa/rGeoCBI/blob/master/vignettes/analysis.Rmd#L10) specifies its required media files for tic to host
* [hosted vignette](https://dbca-wa.github.io/rGeoCBI/articles/analysis.html) now shows media files in popups and reactable row details

**Comment by florianm** [comment]
For future Florian, the intricate pkgdown travis dance goes like this:

* `usethis::use_pkgdown_travis()` creates a branch gh-pages and gitignores docs/
* `travis::browse_travis_token(endpoint = '.org')` opens <https://travis-ci.org/account/preferences> to view Travis API key
* `usethis::edit_r_environ()` to open ~/.Renviron > add `R_TRAVIS_ORG = "tHeAPIToKeN..."`, restart session
* `travis::use_travis_deploy(endpoint = ".org")` creates a deploy key on <https://github.com/dbca-wa/ruODK> > Settings > Deploy keys using the authentication from the Travis CI API token

**Comment by maelle** [comment]
I'm not sure I follow, you want that for building the website before transfer i.e. in the meantime?

Useful refs
https://ropensci.org/technotes/2019/06/07/ropensci-docs/
https://ropensci.org/technotes/2019/12/08/precompute-vignettes/

**Comment by florianm** [comment]
Yep, I'm just experimenting with the travis-built version (media files are not visible yet although the setup is identical to my other, working, package). If anyone builds my vignettes (e.g. the ropensci drake process), the vignettes must know their own media files (images in map popups), so I thought if I solve that problem with travis/pkgdown/gh-pages I can debug issues while things are under my control.

**Comment by maelle** [comment]
Ah ok! Good luck! I don't know drake enough to help.

**Comment by florianm** [comment]
Found the last typo, the ruODK vignettes now include and link to their media files: https://dbca-wa.github.io/ruODK/articles/odata-api.html#map > popups now show photos. 
This should future-proof the vignettes to build anywhere.

**Comment by maelle** [comment]
But don't many ruODK vignettes need access tokens or so? In that case you'll have to precompute them for the rOpenSci docs server (as explained in the tech note link I posted earlier).

**Comment by florianm** [comment]
That's a very good point, and thanks to suggestions by @karissawhiting and @jmt2080ad the vignettes now are refactored to use canned data and included media files. They show (but don't run) the code to download the data live (which would require server credentials), but under the bonnet load the package data instead. Including the media files doesn't even increase the package too much thanks to some vigorous resizing, it's more the 3MB of leaflet dependencies that hurt (the map is central to the data vis).
