### ISSUE TITLE
Encoding the xmlFormId

### ISSUE THREAD

**Issue by matthew-white** [dbca-wa/ruODK#60]
ODK Central recently had an [issue](https://github.com/getodk/central-backend/issues/256) related to URL-encoding: there was a place where we needed to encode the xmlFormId in a URL. It's a subtle thing, so I just wanted to check that ruODK also encodes the xmlFormId in the URLs that it uses for requests!

**Comment by florianm** [comment]
Cheers, Matt! `ruODK` now encodes the form ID using `URLencode(fid, reserved = TRUE)` which, coming from the utils package, doesn't add any extra dependencies.
