### ISSUE TITLE
Using with Kobo Toolbox

### ISSUE THREAD

**Issue by dmenne** [dbca-wa/ruODK#71]
I am a little confused when it comes to the terminology of Kobo, ODK Central, ODK Collect.

Trying to use ruODK with Kobotoolbox. Everything works fine with something like:

`https://kf.kobotoolbox.org/api/v2/assets?format=json` 

in Postman and Basic Authentication. I can also use ODK  Briefcase without problem. The following did not work, though:

```
ruODK::ru_setup(
  fid = "Beispiele",
  url = "https://kf.kobotoolbox.org",
  un = "mylogin",
  pw = "mypassword"
) 
```

**Comment by florianm** [comment]
Hi Dieter,

ruODK is an R client specifically for the ODK Central API, not the KoBo toolbox API, sorry!

[XLSForms](https://docs.getodk.org/xlsform/) and [XForms](https://docs.getodk.org/form-design-intro/) are two different standards for digital forms.
[ODK Collect](https://docs.getodk.org/collect-intro/) is a mobile data capture app.
[ODK Central](https://docs.getodk.org/central-intro/) is the corresponding data clearinghouse from which ODK Collect receives form templates and uploads filled out form instances and media attachmets to. ODK Central [supports XLSForms from version 0.7](https://docs.getodk.org/central-forms/#uploading-a-form-to-odk-central).
KoBo Toolbox is built around [XlsForms](https://www.kobotoolbox.org/) and has a different API to ODK Cental.
While ruODK will likely not work with the KoBo toolbox API, it solves problems around downloading and parsing data which you might be able to build upon in your own R scripts.

Of interest could be:

* [rectangling](https://github.com/dbca-wa/ruODK/blob/master/R/odata_submission_rectangle.R) (un-nesting lists of lists into rectangular data) - at its heart, ruODK uses `tidyr::unnest_wider(names_sep=...)` recursively.
* form schema introspection to determine non-trivial data types which need specific post-processing, see handle_ru_{geopoint, geotrace, geoshape, attachment, datetime}
* parsing of submission data (top level [here](https://github.com/dbca-wa/ruODK/blob/master/R/odata_submission_get.R#L202))

Does this help you at all?

**Comment by dmenne** [comment]
Yes, thanks. I just switched to ODK Central for testing on my server. The R-code might be nice to have, even if I am R-guy by default.

**Comment by florianm** [comment]
Great, give us a yell if you get stuck anywhere between ODK Central and ruODK!

**Comment by dmenne** [comment]
I just migrated to ODK-Central via DigitalOcean and found that the link to ruODK is displayed. Great! Two years ago I had already tried ODK, and it was a rather messy installation. Installation on my own server failed because I alread had nginx and mail server in docker, and I was too lazy to try to fiddle with docker-compose, but installation on a virgin Ubuntu was easy.

**Comment by florianm** [comment]
Tearing up the docker-compose install is a special kind of pain, yep :-)
We managed to run ODK Central in k8s with existing db cluster, mail server, and reverse proxy (ssl certs). I've documented the setup in forum.getodk.org
