### ISSUE TITLE
Put data into separate package

### ISSUE THREAD

**Issue by dmenne** [dbca-wa/ruODK#73]
Documentation of the package is nice! I found it a bit confusing that the sample details (e.g. fq_form_detail) were listed in the documents ("Where the hell did the birds come from"). 

May I suggest that to make the documentation more concise to put the samples in a separate package, or in data()?

**Comment by florianm** [comment]
Thanks, the rOpenSci reviewers and I have put a ton of work into the docs.

My current scope is designed to present a standalone package including test forms, resulting data in raw and parsed form, vignettes built of that data, tests using the packaged data, and finally some carefully compressed media attachments to demonstrate how to link them from leaflet popups.

Some parts like the worked examples in the README (= docs front page) show a (at compile time) live view of the ODK Central sandbox server, which may or may not contain form names with birds. (However I couldn't find any references to birds in my docs or package code).

Thanks for the idea to split out bulky bits, which I'll do if I'd ever submit this package to CRAN. I've got no bandwidth to do so currently, but have added this issue to the "CRAN" milestone.

Lastly, to help me clarify confusing passages in the docs, which document did you find the birds in?

**Comment by dmenne** [comment]
Sorry, as an [ex-zoologist](https://scholar.google.de/citations?hl=de&user=juWZAM4AAAAJ) I should have known that "Conostylis yellow" in fq_data_taxa is not a bird, but a plant.  Long ago..
 
Having test data are nice, and having many is even nicer as test cases when you don't want to do the HTTP.  Too bad R documentation does not separate data from functions

Forget my comment - I was very much in a hurry to get something started and was very disappointed to have installed everything just to find out that queries are not supported.

**Comment by florianm** [comment]
Nice publication record! And I was getting worried that I couldn't find a reference to "bird" anywhere in the package :-D

It's best practice for CRAN R packages to split out supplementary data, *cf.* https://cran.r-project.org/web/packages/vortexRdata/index.html and https://cran.r-project.org/web/packages/vortexR/
When I get the bandwidth to support the additional complexity I'll revisit this issue and split out the data and (heavy) examples.
