### ISSUE TITLE
How to retrieve XForm elements like field labels and hints

### ISSUE THREAD

**Issue by dmenne** [dbca-wa/ruODK#75]
To recreate the form as as pdf-report, I need access to the labels and hints.

Where to find these?

**Comment by dmenne** [comment]
```
cat(paste(form_xml(FALSE), collapse = "\n"), file = "a.xml")
```
Or is there an easier way?

**Comment by florianm** [comment]
Form field labels and hints are contained in the form definition. In contrast, the form_schema only contains database names of form fields and their path in the form, but not presentation elements like labels and hints.

ruODK gets mainly form data against the database names of fields.
If you need other parts of the form definition, you can export the form definition both as XForm and as [XLSForm](https://odkcentral.docs.apiary.io/#reference/forms-and-submissions/'-individual-form/retrieving-form-xls(x)) - the latter only works if you have created the ODK Central form from an XLSform.

ruODK isn't doing anything nice with the XForm XML apart from representing it as a nested list.

I see three ways to re-create the form:
* I you've created the form form XLSForm, you can get a clean-ish XLSForm back out of ODK Central
* If not, , you'd have to parse the XForm XML along the lines of [`form_schema_parse`](https://github.com/dbca-wa/ruODK/blob/master/R/form_schema_parse.R#L46)
* If you have knowledge of the form, you can hard-code the field names and labels in the report. This is probably the fastest way, although not generic.

**Comment by florianm** [comment]
Closing and continuing discussion at #77
