### ISSUE TITLE
Documentation Example of form_schema_parse

### ISSUE THREAD

**Issue by dmenne** [dbca-wa/ruODK#76]
The example in `form_schema_parse`:

```
fs <- form_schema(flatten = FALSE)
fsp <- form_schema_parse(fs) 
# object 'name' not found  fsp 
<- form_schema(parse=TRUE)
 # works
```

**Comment by florianm** [comment]
Thanks, I've updated the docs and added tests. Above docs referred to ODK Central pre 0.8, which returned fiendishly ugly XML form schemas.
