### ISSUE TITLE
Optionally suppress name repair message in odata_submission_get

### ISSUE THREAD

**Issue by dmenne** [dbca-wa/ruODK#79]
It would be nice to be able to suppress the name-repair messages in `odata_submission_get`.
```
new names:
* `@odata.context` -> .odata.context
* `@odata.nextLink` -> .odata.nextLink
```

I tried ` .name_repair = ~ vctrs::vec_as_names(..., quiet = TRUE)` documented for readxl, but this does not work here.  Correct me when there is a dplyr setting to suppress this, I could not find one.

**Comment by florianm** [comment]
There messages come from the guts of tidyr::unnest_wider, likely where it uses [vec_as_names](https://github.com/tidyverse/tidyr/blob/master/R/pack.R#L107) which unfortunately does not take the dots argument through which you could pass `quiet=TRUE`.

You can control [ruODK's verbosity](https://dbca-wa.github.io/ruODK/reference/ru_setup.html) but these tidyr messages (and any other diagnostic messages) can only be silenced if ruODK were to wrap tidyr::unnest_wider in suppressMessages(). I'd rather be too verbose than to hide an error you need for debugging.
Do you agree with this line of thinking?

**Comment by dmenne** [comment]
Currently, I am using suppressMessages, but it is ugly because it hides other stuff.

But unnest_wider has `names_repair` options?

**Comment by florianm** [comment]
Found the squeaky bit - `tibble::as_tibble` needed a muffler. Does this address your suggestion?

**Comment by dmenne** [comment]
Cool ... as we Germans say.
