### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by dmenne** [dbca-wa/ruODK#80]
The "Using ODATA" links referring to R/ruODK on Submissions page of ODK Central are all dead.

**Comment by florianm** [comment]
Thanks Dieter! 
I could verify that three links are broken: two vignettes I've renamed, and the contributing guide. The other links in the modal dialogue do work.
I'm submitting a PR to ODK Central's front-end to fix the three broken links.

**Comment by florianm** [comment]
Workaround for now:

* Vignettes: https://dbca-wa.github.io/ruODK/ > browse "articles" (=vignettes)
* Contributing: https://dbca-wa.github.io/ruODK/ > sidebar has standard link to [contributing](https://dbca-wa.github.io/ruODK/CONTRIBUTING.html)

**Comment by florianm** [comment]
Fix is merged thanks to :racing_car: work by @lognaturel @matthew-white
