### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by arestrom** [dbca-wa/ruODK#81]
## Problem
Installation fails when using `remotes::install_github("dbca-wa/ruODK", dependencies = TRUE)`

Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref master

It looks like the master branch is now called `main`, so installation instructions should probably be edited. Love the package!

**Comment by florianm** [comment]
Hi @arestrom, thanks for the heads-up, I totally missed that!

Installation indeed now needs an explicit mention of the `main` branch in either version of:

```
remotes::install_github("dbca-wa/ruODK@main", dependencies = TRUE)
remotes::install_github("dbca-wa/ruODK", ref = "main", dependencies = TRUE)
```

An update to the docs is underway.
